language: go

os: 
  - linux
  - windows
  - osx

dist: xenial

addons:
  homebrew:
    packages:
      - gcc
      - golang
    update: true

go:
  - 1.x
  - "1.10"
  - 1.11.x
  - master

compiler:
  - gcc
  - clang

services:
  - docker

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y --no-install-recommends gcc; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew upgrade go          ; fi

install: true

script:
  - env GOPATH=$(pwd) go build indole

deploy:
  - deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: 
    - indole-linux.zip
    - indole-windows.zip
    - windole-windows.zip
    skip_cleanup: true
    on:
      tags: true
